language: php

php:
  - 7.2
  - 7.3

env:
  - PHPSPEC_VERSION=~5.1.0 LARAVEL_VERSION=5.7.*
  - PHPSPEC_VERSION=^6.0  LARAVEL_VERSION=^6.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer require --no-update "phpspec/phpspec:${PHPSPEC_VERSION}"
  - travis_retry composer require --no-update "laravel/framework:${LARAVEL_VERSION}"

install:
  - composer update

script:
  - ./bin/phpspec run
